#!/usr/bin/env python3

# Copyright © 2022 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

import argparse
import io
import json
import re
import urllib.parse
import urllib.request

0_0  # Python >= 3.6 is required

user_agent = 'gitlab-toolbox (https://github.com/jwilk/gitlab-toolbox)'

def wget(url):
    headers = {'User-Agent': user_agent}
    request = urllib.request.Request(url, headers=headers)
    return urllib.request.urlopen(request)

def wget_json(url):
    with wget(url) as fp:
        with io.TextIOWrapper(fp, encoding='UTF-8') as tfp:
            return json.load(tfp)

def fmt_date(d):
    d = re.sub('[.]\d+', '', d)
    d = d.replace('T', ' ')
    return d

def fmt_user(user, url):
    url = urllib.request.urljoin(url, user['path'])
    username = user['username']
    return f'{username} <{url}>'

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('url', metavar='URL')
    opts = ap.parse_args()
    jurl = f'{opts.url}.json'
    data = wget_json(jurl)
    print('Location:', urllib.parse.urljoin(opts.url, data['web_url']))
    print('Title:', data['title'])
    print('Type:', data['type'])
    print('Created-At:', fmt_date(data['created_at']))
    print('Updated-At:', fmt_date(data['updated_at']))
    labels = [label['title'] for label in data['labels']]
    if labels:
        print('Labels:', *labels)
    print()
    print(data['description'])
    jurl = f'{opts.url}/discussions.json'
    data = wget_json(jurl)
    for item in data:
        for note in item['notes']:
            print()
            print('-' * 72)
            url = note['noteable_note_url']
            if url:
                print('Location:', url)
            print('From:', fmt_user(note['author'], url or jurl))
            print()
            print(note['note'])

if __name__ == '__main__':
    main()

# vim:ts=4 sts=4 sw=4 et
