name: CI
permissions: {}
on:
- push
- pull_request
jobs:
  main:
    strategy:
      matrix:
        include:
        - python-version: '3.8'
          os: ubuntu-22.04
        - python-version: '3.9'
          os: ubuntu-22.04
        - python-version: '3.10'
          os: ubuntu-22.04
        - python-version: '3.11'
          os: ubuntu-22.04
        - python-version: '3.12'
          os: ubuntu-22.04
        - python-version: '3.13'
          os: ubuntu-24.04
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v4
    - name: set up Python ${{matrix.python-version}}
      uses: actions/setup-python@v5
      with:
        python-version: ${{matrix.python-version}}
    - name: run tests
      run: |
         ZGLAB_NETWORK_TESTING=1 prove -v
    - name: run more network tests
      run: |
        ./zglab https://gitlab.com/inkscape/inkscape/-/issues/50
    - name: run pydiatra
      run: |
        python3 -m pip install pydiatra
        python3 -m pydiatra -v .
    - name: run pyflakes
      run: |
        python3 -m pip install pyflakes
        python3 -m pyflakes .
    - name: check README syntax
      run: |
        python3 -m pip install restructuredtext-lint pygments
        rst-lint --level=info --encoding=UTF-8 README

# vim:ts=2 sts=2 sw=2 et
